[package]
name = "dnject"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]
members = ["injector"]

[dependencies]
sysinfo = "0.26"
cpp_core = "0.6"
qt_core = "0.5"
qt_gui = "0.5"
qt_widgets = "0.5"
qt_ui_tools = "0.5"
qt_core_custom_events = "0.2"

[build-dependencies]
qt_ritual_build = "0.5"
