[package]
name = "rinject"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["injector"]

[dependencies]
sysinfo = "0.24.6"
slint = "0.2.5"
log = { version = "0.4.17", features = ["std"] }
chrono = "0.4.19"

[build-dependencies]
slint-build = "0.2.5"