import { Button, CheckBox, ComboBox, GroupBox, HorizontalBox, VerticalBox, StandardListView, TextEdit } from "std-widgets.slint";

MainWindow := Window {
	min-width: 450px;
    max-width: 450px;
    preferred-height: 900px;
    title: "rinject";

	// Callbacks to rust
	callback fetch-proc-list(string) -> [StandardListViewItem];
	callback inject(StandardListViewItem, [StandardListViewItem]);
	// Slint doesn't have array manipulation built in
    callback add-library([StandardListViewItem]) -> [StandardListViewItem];
    callback mod-library-list([StandardListViewItem], int, bool) -> [StandardListViewItem];
    callback quit();  // Slint seriously doesn't this built in??

	// Callbacks from rust
    callback log(string);
    log(str) => { LogView.text = str + LogView.text }
    callback refresh-proc-list();
    refresh-proc-list() => { RefreshButton.clicked() }

	// These are only needed because slint doesn't support conditional compilation
	// So rust has to populate the combobox options at init itself
    property<[string]> proc-modes <=> ModeSelector.model;
    property<string> proc-sel <=> ModeSelector.current-value;

    VerticalBox {
        HorizontalBox {
	        alignment: center;
	        vertical-stretch: 0;
            Text {
				vertical-stretch: 0;
                text: root.title;
                font-size: 30px;
                max-height: 0px;
            }
        }

		GroupBox {
			title: "Process";
			VerticalBox {
				HorizontalBox {
					ProcListView := StandardListView {
						vertical-stretch: 1;
						min-height: 200px;
					}
					RefreshButton := Button {
						width: 35px;
						text: "↻";
						clicked => { ProcListView.model = fetch-proc-list(ModeSelector.current-value) }
					}
				}
				// TODO Radio buttons would be a better fit, but slint doesn't have those
				ModeSelector := ComboBox {
					max-height: 0px;
					selected(mode) => { ProcListView.model = fetch-proc-list(mode) }
				}
//				HorizontalBox {
//					alignment: center;
//					FilterOwner := CheckBox {
//						text: "Owner Only";
//					}
//					WineMode := CheckBox {
//						text: "Wine";
//						visible: false;
//					}
//				}
			}
		}

		GroupBox {
			title: "Target Library";
			VerticalBox {
				HorizontalBox {
					LibListView := StandardListView {
						vertical-stretch: 0.3;
						min-height: 30px;
					}
					VerticalLayout {
						width: 35px;
						Button {
							text: "+";
							clicked => {
								LibListView.model = add-library(LibListView.model);
								LibListView.current-item = 0;
							}
						}
						Button {
							text: "🠑";
							enabled: LibListView.model.length > 0;
							clicked => {
								if (LibListView.current-item > 0) {
									LibListView.model = mod-library-list(LibListView.model, LibListView.current-item, true);
									LibListView.current-item -= 1;
								}
							}
						}
						Button {
							text: "-";
							enabled: LibListView.model.length > 0;
							clicked => {
								if (LibListView.current-item >= 0) {
									LibListView.model = mod-library-list(LibListView.model, LibListView.current-item, false);
									if (LibListView.current-item > 0) {
										LibListView.current-item -= 1;
									}
								}
							}
						}
					}
				}
			}
		}
		// TODO Good place for a progress bar which slint doesn't have

		// TODO Add button to elevate privileges
		// On linux, this would mean giving CAP_SYS_PTRACE to attach and r/w mem,
		// And CAP_DAC_READ_SEARCH to read from the target /proc file (or CAP_DAC_OVERRIDE to write too)
		// https://docs.rs/caps/latest/caps/
		// https://man7.org/linux/man-pages/man7/capabilities.7.html
		HorizontalBox {
			QuitCheck := CheckBox {
				text: "Quit on finish";
			}
			Button {
				text: "Inject";
				enabled: ProcListView.current-item >= 0 && LibListView.model.length > 0;
				clicked => {
					inject(ProcListView.model[ProcListView.current-item], LibListView.model);
					if (QuitCheck.checked) { root.quit() }
				}
			}
		}
		GroupBox {
			title: "Log";
			LogView := TextEdit {
				min-height: 100px;
				read-only: true;
				max-height: 150px;  // For some reason this element hogs all the stretch
//				vertical-stretch: 0.1;
			}
		}
    }
}
