import { ScrollView, Button, CheckBox, SpinBox, Slider, GroupBox, LineEdit, StandardListView,
    ComboBox, HorizontalBox, VerticalBox, GridBox, TabWidget, TextEdit, AboutSlint, ListView } from "std-widgets.slint";

MainWindow := Window {
	min-width: 450px;
    max-width: 450px;
    preferred-height: 900px;
    title: "rinject";

	// Callbacks to rust
	callback refresh-proc-list() -> [StandardListViewItem];
	callback inject(StandardListViewItem, [StandardListViewItem]);
	// Slint doesn't have array manipulation built in
    callback add-library([StandardListViewItem]) -> [StandardListViewItem];
    callback mod-library-list([StandardListViewItem], int, bool) -> [StandardListViewItem];
    callback quit();  // Slint seriously doesn't this built in??

	// Callbacks from rust
    callback log(string);
    log(str) => { LogView.text = str + LogView.text }

//    property<[StandardListViewItem]> proc-list <=> ProcListView.model;
//    property<int> proc-selected-index <=> ProcListView.current-item;
    property<bool> filter-owner <=> FilterOwner.checked;
    property<bool> wine-mode <=> WineMode.checked;
    property<bool> wine-mode-available <=> WineMode.visible;
    property<[StandardListViewItem]> lib-list <=> LibListView.model;
    property<int> lib-selected-index <=> LibListView.current-item;

    VerticalBox {
        HorizontalBox {
	        alignment: center;
	        vertical-stretch: 0;
            Text {
				vertical-stretch: 0;
                text: root.title;
                font-size: 30px;
                max-height: 0px;
            }
        }

		GroupBox {
			title: "Process";
			VerticalBox {
				HorizontalBox {
					ProcListView := StandardListView {
						vertical-stretch: 1;
						min-height: 200px;
						model: [ { text: "Process list loading"} ];
					}
					Button {
						width: 35px;
						text: "↻";
						clicked => { ProcListView.model = refresh-proc-list() }
					}
				}
				HorizontalBox {
					alignment: center;
					FilterOwner := CheckBox {
						text: "Owner Only";
					}
					WineMode := CheckBox {
						text: "Wine";
						visible: false;
					}
				}
			}
		}

		GroupBox {
			title: "Target Library";
			VerticalBox {
				HorizontalBox {
					LibListView := StandardListView {
						vertical-stretch: 0.3;
						min-height: 30px;
					}
					VerticalBox {
						width: 50px;
						Button {
							text: "+";
							clicked => {
								LibListView.model = add-library(LibListView.model);
								LibListView.current-item = 0;
							}
						}
						Button {
							text: "🠑";
							clicked => {
								if (LibListView.current-item > 0) {
									LibListView.model = mod-library-list(LibListView.model, LibListView.current-item, true);
									LibListView.current-item -= 1;
								}
							}
						}
						Button {
							text: "-";
							clicked => {
								if (LibListView.current-item >= 0) {
									LibListView.model = mod-library-list(LibListView.model, LibListView.current-item, false);
									if (LibListView.current-item > 0) {
										LibListView.current-item -= 1;
									}
								}
							}
						}
					}
				}
			}
		}
		// TODO maybe add auth prompt to elevate privileges
		HorizontalBox {
			QuitCheck := CheckBox {
				text: "Quit on finish";
			}
			Button {
				text: "Inject";
				clicked => {
					inject(ProcListView.model[ProcListView.current-item], LibListView.model);
					if (QuitCheck.checked) { root.quit() }
				}
			}
		}
		GroupBox {
			title: "Log";
			LogView := TextEdit {
				min-height: 100px;
				read-only: true;
				max-height: 100px;  // For some reason this element hogs all the stretch
//				vertical-stretch: 0.1;
			}
		}
    }
}
